name: ufg
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP
  dartz: ^0.10.1
  supabase_flutter: ^2.9.1
  flutter_secure_storage: ^11.0.0
  provider: ^6.1.5
  google_fonts: ^8.2.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.1
  shared_preferences: ^2.5.3
  iconsax_flutter: ^1.0.1
  go_router: ^17.5.0
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.3.0
  otp_text_field: ^1.1.5
  dio: ^5.11.0
  file_picker: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/env/.env
    - assets/env/.env.local

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

