default_platform(:android)

platform :android do

  desc "Build and distribute APK to Firebase testers"
  lane :beta do

    Dir.chdir("..") do
      sh("flutter pub get")
      # sh("flutter test")
      sh("flutter build apk --release")
    end

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: ENV["FIREBASE_TESTER_GROUP"],
      release_notes: ENV["RELEASE_NOTES"]
    )

  end

end